spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/bwd
spring.datasource.username=root
spring.datasource.password=Mysqlkaleb2005#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Optional Hibernate property for schema management (create, update, validate, none)
#spring.jpa.hibernate.ddl-auto=update
